
solution: ./src/Examples/HasSurvivingMutants/HasSurvivingMutants.sln

testAssemblies:
    - ./src/Examples/HasSurvivingMutants/Tests/bin/Release/HasSurvivingMutants.Tests.dll

nunitTestRunner: ./tools/NUnit/nunit3-console.exe

projectFilters:
    - HasSurvivingMutants.Implementation
