
solution: .\src\Examples\HasSurvivingMutants\HasSurvivingMutants.sln

projectFilters:
    - HasSurvivingMutants.MoreImplementation

testProjectFilters:
    - HasSurvivingMutants.Tests
    - HasSurvivingMutants.MoreTests
