
solution: .\src\Examples\HasSurvivingMutants\HasSurvivingMutants.sln

testAssemblies:
    - .\src\Examples\HasSurvivingMutants\Tests\bin\Debug\HasSurvivingMutants.Tests.dll

projectFilters:
    - HasSurvivingMutants.Implementation